target-version = "py312"
line-length = 120
lint.select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "C",     # flake8-comprehensions
    "B",     # flake8-bugbear
    "D",     # pydocstyle
    "ASYNC", # flake8-async
    "ANN",   # flake8-annotations
    "RET",   # flake8-return
    "SIM",   # flake8-simplify
    "S",     # flake8-bandit
    "PGH",   # pygrep-hooks
    "PL",    # pylint
    "N",     # pep8-naming
    "UP",    # pyupgrade
    "ERA",   # eradicate
]
lint.ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D205", # 1 blank line required between summary line and description
    "D213", # Multi-line docstring summary should start at the second line
]

[lint.per-file-ignores]
"tests/*.py" = [
    "ARG005",  # Unused lambda argument
    "FBT001",  # Boolean positional arg in function definition
    "PLR2004",  # Magic value used in comparison
    "S101",  # Use of assert detected
]

[lint.pydocstyle]
convention = "google"
