name: Test
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install copier==9.3.1
      - name: Install system dependencies
        run: |
          curl -LsSf https://astral.sh/uv/0.4.6/install.sh | sh
          sudo apt install git
          git clone --branch v1.11.0 https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      - name: Run tests
        run: make test
